---
- hosts: localhost
  gather_facts: no
  vars:
    vcenter_server: "192.168.136.128"
    vcenter_user: "root"
    vcenter_pass: "admin@123"
  tasks:
  - name: Create a New VM without template
    vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      name: test_vm_0001    
      guest_id: centos64Guest
      folder: /
      disk:
      - size_gb: 10
        type: thin
        datastore: datastore1
      hardware:
        memory_mb: 512
        num_cpus: 1
        scsi: paravirtual
      networks:
      - name: VM Network      
        device_type: vmxnet3        
    delegate_to: localhost
